// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyFilterProtos.proto

package HBaseAPI.Filter;

public final class MyFilterProtos {
  private MyFilterProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RangeFilterOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 xmin = 1;
    /**
     * <code>required int32 xmin = 1;</code>
     */
    boolean hasXmin();
    /**
     * <code>required int32 xmin = 1;</code>
     */
    int getXmin();

    // required int32 xmax = 2;
    /**
     * <code>required int32 xmax = 2;</code>
     */
    boolean hasXmax();
    /**
     * <code>required int32 xmax = 2;</code>
     */
    int getXmax();

    // required int32 ymin = 3;
    /**
     * <code>required int32 ymin = 3;</code>
     */
    boolean hasYmin();
    /**
     * <code>required int32 ymin = 3;</code>
     */
    int getYmin();

    // required int32 ymax = 4;
    /**
     * <code>required int32 ymax = 4;</code>
     */
    boolean hasYmax();
    /**
     * <code>required int32 ymax = 4;</code>
     */
    int getYmax();
  }
  /**
   * Protobuf type {@code RangeFilter}
   */
  public static final class RangeFilter extends
      com.google.protobuf.GeneratedMessage
      implements RangeFilterOrBuilder {
    // Use RangeFilter.newBuilder() to construct.
    private RangeFilter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RangeFilter(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RangeFilter defaultInstance;
    public static RangeFilter getDefaultInstance() {
      return defaultInstance;
    }

    public RangeFilter getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RangeFilter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              xmin_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              xmax_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              ymin_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ymax_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyFilterProtos.internal_static_RangeFilter_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyFilterProtos.internal_static_RangeFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RangeFilter.class, Builder.class);
    }

    public static com.google.protobuf.Parser<RangeFilter> PARSER =
        new com.google.protobuf.AbstractParser<RangeFilter>() {
      public RangeFilter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RangeFilter(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<RangeFilter> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 xmin = 1;
    public static final int XMIN_FIELD_NUMBER = 1;
    private int xmin_;
    /**
     * <code>required int32 xmin = 1;</code>
     */
    public boolean hasXmin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 xmin = 1;</code>
     */
    public int getXmin() {
      return xmin_;
    }

    // required int32 xmax = 2;
    public static final int XMAX_FIELD_NUMBER = 2;
    private int xmax_;
    /**
     * <code>required int32 xmax = 2;</code>
     */
    public boolean hasXmax() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 xmax = 2;</code>
     */
    public int getXmax() {
      return xmax_;
    }

    // required int32 ymin = 3;
    public static final int YMIN_FIELD_NUMBER = 3;
    private int ymin_;
    /**
     * <code>required int32 ymin = 3;</code>
     */
    public boolean hasYmin() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 ymin = 3;</code>
     */
    public int getYmin() {
      return ymin_;
    }

    // required int32 ymax = 4;
    public static final int YMAX_FIELD_NUMBER = 4;
    private int ymax_;
    /**
     * <code>required int32 ymax = 4;</code>
     */
    public boolean hasYmax() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 ymax = 4;</code>
     */
    public int getYmax() {
      return ymax_;
    }

    private void initFields() {
      xmin_ = 0;
      xmax_ = 0;
      ymin_ = 0;
      ymax_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasXmin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasXmax()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYmin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYmax()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, xmin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, xmax_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, ymin_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, ymax_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, xmin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, xmax_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ymin_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, ymax_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RangeFilter)) {
        return super.equals(obj);
      }
      RangeFilter other = (RangeFilter) obj;

      boolean result = true;
      result = result && (hasXmin() == other.hasXmin());
      if (hasXmin()) {
        result = result && (getXmin()
            == other.getXmin());
      }
      result = result && (hasXmax() == other.hasXmax());
      if (hasXmax()) {
        result = result && (getXmax()
            == other.getXmax());
      }
      result = result && (hasYmin() == other.hasYmin());
      if (hasYmin()) {
        result = result && (getYmin()
            == other.getYmin());
      }
      result = result && (hasYmax() == other.hasYmax());
      if (hasYmax()) {
        result = result && (getYmax()
            == other.getYmax());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasXmin()) {
        hash = (37 * hash) + XMIN_FIELD_NUMBER;
        hash = (53 * hash) + getXmin();
      }
      if (hasXmax()) {
        hash = (37 * hash) + XMAX_FIELD_NUMBER;
        hash = (53 * hash) + getXmax();
      }
      if (hasYmin()) {
        hash = (37 * hash) + YMIN_FIELD_NUMBER;
        hash = (53 * hash) + getYmin();
      }
      if (hasYmax()) {
        hash = (37 * hash) + YMAX_FIELD_NUMBER;
        hash = (53 * hash) + getYmax();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RangeFilter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RangeFilter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RangeFilter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RangeFilter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RangeFilter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RangeFilter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RangeFilter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RangeFilter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RangeFilter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RangeFilter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RangeFilter prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RangeFilter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RangeFilterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyFilterProtos.internal_static_RangeFilter_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyFilterProtos.internal_static_RangeFilter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RangeFilter.class, Builder.class);
      }

      // Construct using com.potree.mdhbase.Filter.MyFilterProtos.RangeFilter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        xmin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        xmax_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        ymin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        ymax_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyFilterProtos.internal_static_RangeFilter_descriptor;
      }

      public RangeFilter getDefaultInstanceForType() {
        return RangeFilter.getDefaultInstance();
      }

      public RangeFilter build() {
        RangeFilter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RangeFilter buildPartial() {
        RangeFilter result = new RangeFilter(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.xmin_ = xmin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.xmax_ = xmax_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ymin_ = ymin_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ymax_ = ymax_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RangeFilter) {
          return mergeFrom((RangeFilter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RangeFilter other) {
        if (other == RangeFilter.getDefaultInstance()) return this;
        if (other.hasXmin()) {
          setXmin(other.getXmin());
        }
        if (other.hasXmax()) {
          setXmax(other.getXmax());
        }
        if (other.hasYmin()) {
          setYmin(other.getYmin());
        }
        if (other.hasYmax()) {
          setYmax(other.getYmax());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasXmin()) {
          
          return false;
        }
        if (!hasXmax()) {
          
          return false;
        }
        if (!hasYmin()) {
          
          return false;
        }
        if (!hasYmax()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RangeFilter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RangeFilter) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 xmin = 1;
      private int xmin_ ;
      /**
       * <code>required int32 xmin = 1;</code>
       */
      public boolean hasXmin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 xmin = 1;</code>
       */
      public int getXmin() {
        return xmin_;
      }
      /**
       * <code>required int32 xmin = 1;</code>
       */
      public Builder setXmin(int value) {
        bitField0_ |= 0x00000001;
        xmin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 xmin = 1;</code>
       */
      public Builder clearXmin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        xmin_ = 0;
        onChanged();
        return this;
      }

      // required int32 xmax = 2;
      private int xmax_ ;
      /**
       * <code>required int32 xmax = 2;</code>
       */
      public boolean hasXmax() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 xmax = 2;</code>
       */
      public int getXmax() {
        return xmax_;
      }
      /**
       * <code>required int32 xmax = 2;</code>
       */
      public Builder setXmax(int value) {
        bitField0_ |= 0x00000002;
        xmax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 xmax = 2;</code>
       */
      public Builder clearXmax() {
        bitField0_ = (bitField0_ & ~0x00000002);
        xmax_ = 0;
        onChanged();
        return this;
      }

      // required int32 ymin = 3;
      private int ymin_ ;
      /**
       * <code>required int32 ymin = 3;</code>
       */
      public boolean hasYmin() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 ymin = 3;</code>
       */
      public int getYmin() {
        return ymin_;
      }
      /**
       * <code>required int32 ymin = 3;</code>
       */
      public Builder setYmin(int value) {
        bitField0_ |= 0x00000004;
        ymin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ymin = 3;</code>
       */
      public Builder clearYmin() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ymin_ = 0;
        onChanged();
        return this;
      }

      // required int32 ymax = 4;
      private int ymax_ ;
      /**
       * <code>required int32 ymax = 4;</code>
       */
      public boolean hasYmax() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 ymax = 4;</code>
       */
      public int getYmax() {
        return ymax_;
      }
      /**
       * <code>required int32 ymax = 4;</code>
       */
      public Builder setYmax(int value) {
        bitField0_ |= 0x00000008;
        ymax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ymax = 4;</code>
       */
      public Builder clearYmax() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ymax_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RangeFilter)
    }

    static {
      defaultInstance = new RangeFilter(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RangeFilter)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RangeFilter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RangeFilter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024MyFilterProtos.proto\"E\n\013RangeFilter\022\014\n" +
      "\004xmin\030\001 \002(\005\022\014\n\004xmax\030\002 \002(\005\022\014\n\004ymin\030\003 \002(\005\022" +
      "\014\n\004ymax\030\004 \002(\005B,\n\022com.potree.mdhbaseB\016MyF" +
      "ilterProtosH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RangeFilter_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RangeFilter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RangeFilter_descriptor,
              new String[] { "Xmin", "Xmax", "Ymin", "Ymax", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
